# Generated by Django 4.2.19 on 2025-03-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('receive', 'Received'), ('in-transit', 'In Transit'), ('delivered', 'Delivered')], default='receive', max_length=50)),
                ('priority_level', models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], default='medium', max_length=30)),
                ('destination_address', models.CharField(max_length=300)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
        ),
    ]
