# Generated by Django 4.2.19 on 2025-03-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sku', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('stock_threshold', models.IntegerField(default=50)),
                ('restock', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=300)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='logistics_app.product'),
            preserve_default=False,
        ),
    ]
