# Generated by Django 4.2.19 on 2025-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('High', 'High')], default='medium', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Receive', 'Received'), ('In-Transit', 'In Transit'), ('Delivered', 'Delivered')], default='receive', max_length=50),
        ),
    ]
