# Generated by Django 4.2.19 on 2025-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0003_slugs_products_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
