# Generated by Django 4.2.19 on 2025-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0004_alter_order_priority_level_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In-Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Receive', max_length=50),
        ),
    ]
