# Generated by Django 4.2.19 on 2025-03-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0004_alter_order_priority_level_alter_order_status'),
        ('logistics_app', '0006_date_and_min_value'),
    ]

    operations = [
    ]
