# Generated by Django 4.2.19 on 2025-03-08 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0005_alter_order_status'),
        ('logistics_app', '0007_merge_20250306_0153'),
    ]

    operations = [
    ]
