# Generated by Django 4.2.19 on 2025-03-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0009_order_quantity_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
