# Generated by Django 4.2.19 on 2025-03-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0009_inventory_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
