# Generated by Django 4.2.19 on 2025-03-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0010_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_app.inventory'),
        ),
    ]
