# Generated by Django 4.2.19 on 2025-03-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0011_order_route_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='route_coords',
        ),
        migrations.RemoveField(
            model_name='order',
            name='route_eta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='route_miles',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_coords', models.JSONField(blank=True, null=True)),
                ('route_eta', models.FloatField(blank=True, null=True)),
                ('route_miles', models.FloatField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In-Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Receive', max_length=50)),
                ('status_msg', models.CharField(blank=True, max_length=450, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics_app.order')),
            ],
        ),
    ]
