# Generated by Django 4.2.19 on 2025-03-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0013_date_time_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
