# Generated by Django 4.2.19 on 2025-03-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0011_orderitem_inventory'),
        ('logistics_app', '0014_alter_orderstatushistory_last_updated'),
    ]

    operations = [
    ]
