# Generated by Django 4.2.19 on 2025-03-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0015_merge_20250310_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='logistics_app.inventory'),
        ),
    ]
