# Generated by Django 4.2.19 on 2025-03-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0016_alter_orderitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='example_default@example.com', max_length=350),
            preserve_default=False,
        ),
    ]
